name: Scheduled rebuild

on:
  schedule:
    - cron:  '0,30 * * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Call build hook
      env:
        BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
      run: curl -X POST -d {} $BUILD_HOOK_URL
