name: Scheduled rebuild

on:
  schedule:
    - cron:  '0 * * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with Gradle
      env: BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
      run: curl -X POST -d {} $BUILD_HOOK_URL
